"""Create simple_flows table

Revision ID: 0a54ee9e78fa
Revises: eb0ef2d522a1
Create Date: 2025-12-11 14:20:58.928359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a54ee9e78fa'
down_revision: Union[str, None] = 'eb0ef2d522a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.String(length=50), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('max_images', sa.Integer(), nullable=False),
    sa.Column('engines', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('downloaded_images', sa.Integer(), nullable=False),
    sa.Column('validated_images', sa.Integer(), nullable=False),
    sa.Column('failed_images', sa.Integer(), nullable=False),
    sa.Column('task_ids', sa.JSON(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('failed_tasks', sa.Integer(), nullable=False),
    sa.Column('output_path', sa.String(length=500), nullable=False),
    sa.Column('output_name', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_flows_flow_id'), 'simple_flows', ['flow_id'], unique=True)
    op.create_index(op.f('ix_simple_flows_status'), 'simple_flows', ['status'], unique=False)
    op.drop_index(op.f('ix_flows_flow_id'), table_name='flows')
    op.drop_index(op.f('ix_flows_status'), table_name='flows')
    op.drop_table('flows')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_created_at', table_name='notifications', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('flows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flow_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('max_images', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('engines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('downloaded_images', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('validated_images', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_images', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_tasks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('output_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('output_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('flows_pkey'))
    )
    op.create_index(op.f('ix_flows_status'), 'flows', ['status'], unique=False)
    op.create_index(op.f('ix_flows_flow_id'), 'flows', ['flow_id'], unique=True)
    op.drop_index(op.f('ix_simple_flows_status'), table_name='simple_flows')
    op.drop_index(op.f('ix_simple_flows_flow_id'), table_name='simple_flows')
    op.drop_table('simple_flows')
    # ### end Alembic commands ###
