"""Add Flow table for simple crawl operations

Revision ID: eb0ef2d522a1
Revises: f379add8683c
Create Date: 2025-12-11 14:18:57.361154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0ef2d522a1'
down_revision: Union[str, None] = 'f379add8683c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.String(length=50), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('max_images', sa.Integer(), nullable=False),
    sa.Column('engines', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('downloaded_images', sa.Integer(), nullable=False),
    sa.Column('validated_images', sa.Integer(), nullable=False),
    sa.Column('failed_images', sa.Integer(), nullable=False),
    sa.Column('task_ids', sa.JSON(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('failed_tasks', sa.Integer(), nullable=False),
    sa.Column('output_path', sa.String(length=500), nullable=False),
    sa.Column('output_name', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_flow_id'), 'flows', ['flow_id'], unique=True)
    op.create_index(op.f('ix_flows_status'), 'flows', ['status'], unique=False)
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_created_at', table_name='notifications', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_flows_status'), table_name='flows')
    op.drop_index(op.f('ix_flows_flow_id'), table_name='flows')
    op.drop_table('flows')
    # ### end Alembic commands ###
