"""
Authentication utility endpoints for Supabase Auth integration.

This module provides utility endpoints for Supabase Auth integration.
All authentication uses Supabase Auth - NO custom JWT generation.

These endpoints provide:
- Login (proxied through backend, returns Supabase tokens)
- User profile retrieval
- Token verification
- Profile synchronization between Supabase Auth and profiles table

Note: Authentication flow:
1. User calls /api/v1/auth/login with credentials
2. Backend forwards to Supabase Auth
3. Supabase returns JWT tokens (access_token, refresh_token)
4. Frontend stores tokens and uses in Authorization header
5. Backend verifies tokens using get_current_user dependency
"""

from fastapi import APIRouter, HTTPException, status as http_status

from backend.api.types import CurrentUser, SupabaseAuthServiceDep
from backend.api.v1.response_models import get_common_responses
from backend.schemas.user import (
    UserResponse,
    TokenVerificationResponse,
    ProfileSyncResponse,
    UserLogin,
    TokenResponse,
)

__all__ = ['router']

router = APIRouter(
    tags=["Authentication"],
    responses=get_common_responses(401, 500),
)


@router.post(
    "/login",
    response_model=TokenResponse,
    summary="Login User",
    description="Authenticate user with email and password via Supabase Auth. Returns Supabase JWT tokens.",
    response_description="Authentication tokens (access_token, refresh_token)",
    operation_id="loginUser",
    responses={
        200: {
            "description": "Login successful",
            "content": {
                "application/json": {
                    "example": {
                        "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                        "token_type": "bearer",
                        "expires_in": 3600
                    }
                }
            }
        },
        401: {
            "description": "Invalid credentials",
            "content": {
                "application/json": {
                    "example": {"detail": "Invalid email or password"}
                }
            }
        },
        **get_common_responses(422, 500)
    }
)
async def login(
    credentials: UserLogin,
    auth_service: SupabaseAuthServiceDep,
) -> TokenResponse:
    """
    Login user with email and password.

    Authenticates user via Supabase Auth and returns JWT tokens.
    These tokens are generated by Supabase (NOT custom JWT).

    **Usage:**
    ```bash
    curl -X POST http://localhost:8000/api/v1/auth/login \\
      -H "Content-Type: application/json" \\
      -d '{"email": "user@example.com", "password": "password123"}'
    ```

    **Response:**
    - `access_token`: Use in Authorization header as `Bearer <token>`
    - `refresh_token`: Use to get new access token when expired
    - `expires_in`: Token expiration time in seconds

    **Next Steps:**
    1. Store the access_token securely
    2. Include in API requests: `Authorization: Bearer <access_token>`
    3. Use refresh_token to get new access_token before expiration

    Args:
        credentials: User email and password
        auth_service: Supabase authentication service

    Returns:
        TokenResponse with Supabase JWT tokens

    Raises:
        HTTPException: 401 if credentials are invalid
        HTTPException: 500 if login fails
    """
    try:
        # Sign in using Supabase Auth
        response = auth_service.supabase.auth.sign_in_with_password({
            "email": credentials.email,
            "password": credentials.password.get_secret_value()
        })

        # Check if login was successful
        if not response.session:
            raise HTTPException(
                status_code=http_status.HTTP_401_UNAUTHORIZED,
                detail="Invalid email or password"
            )

        # Ensure user profile exists in profiles table
        try:
            await auth_service.get_user_profile(response.user.id)
        except Exception:
            # Create profile if it doesn't exist
            await auth_service.create_user_profile({
                "id": response.user.id,
                "email": response.user.email,
                "full_name": response.user.user_metadata.get("full_name", ""),
            })

        # Log successful login
        auth_service.log_operation(
            "user_login",
            user_id=response.user.id
        )

        # Return Supabase tokens
        return TokenResponse(
            access_token=response.session.access_token,
            refresh_token=response.session.refresh_token,
            token_type="bearer",
            expires_in=response.session.expires_in
        )

    except HTTPException:
        raise
    except Exception as e:
        auth_service.logger.error(f"Login failed: {str(e)}")
        raise HTTPException(
            status_code=http_status.HTTP_401_UNAUTHORIZED,
            detail="Invalid email or password"
        )


@router.get(
    "/me",
    response_model=UserResponse,
    summary="Get Current User Profile",
    description="Retrieve the authenticated user's profile information from Supabase Auth.",
    response_description="User profile with email, name, and account details",
    operation_id="getCurrentUserProfile",
    responses={
        200: {
            "description": "Successfully retrieved user profile",
            "content": {
                "application/json": {
                    "example": {
                        "id": "123e4567-e89b-12d3-a456-426614174000",
                        "email": "user@example.com",
                        "full_name": "John Doe",
                        "is_active": True,
                        "created_at": "2024-01-01T00:00:00Z",
                        "updated_at": "2024-01-01T00:00:00Z"
                    }
                }
            }
        },
        **get_common_responses(401, 500)
    }
)
async def get_current_user_profile(
    current_user: CurrentUser,
    auth_service: SupabaseAuthServiceDep,
) -> UserResponse:
    """
    Get current authenticated user profile.

    Returns the profile information for the currently authenticated user
    based on the Supabase JWT token provided in the Authorization header.

    **Authentication Required:** Bearer token from Supabase Auth

    Args:
        current_user: Current authenticated user from dependency
        auth_service: Supabase authentication service

    Returns:
        Current user profile information

    Raises:
        HTTPException: If user profile is not found or token is invalid
    """
    try:
        profile = current_user["profile"]

        return UserResponse(
            id=profile["id"],
            email=profile["email"],
            full_name=profile.get("full_name", ""),
            is_active=True,  # Supabase users are active by default
            created_at=profile["created_at"],
            updated_at=profile["updated_at"]
        )

    except Exception as e:
        raise HTTPException(
            status_code=http_status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to retrieve user profile"
        )


@router.post(
    "/verify-token",
    response_model=TokenVerificationResponse,
    summary="Verify JWT Token",
    description="Validate a Supabase JWT token and return user information if valid.",
    response_description="Token validation result with user details",
    operation_id="verifyAuthToken",
    responses={
        200: {
            "description": "Token is valid",
            "content": {
                "application/json": {
                    "example": {
                        "valid": True,
                        "user": {
                            "id": "123e4567-e89b-12d3-a456-426614174000",
                            "email": "user@example.com",
                            "profile": {
                                "full_name": "John Doe",
                                "avatar_url": "https://example.com/avatar.jpg"
                            }
                        }
                    }
                }
            }
        },
        **get_common_responses(401, 500)
    }
)
async def verify_token(
    current_user: CurrentUser
) -> TokenVerificationResponse:
    """
    Verify Supabase JWT token and return user information.

    This endpoint validates the JWT token provided in the Authorization header
    and returns the associated user information if the token is valid.

    **Use Case:** Frontend can use this to check if a stored token is still valid
    before making authenticated requests.

    **Authentication Required:** Bearer token from Supabase Auth

    Args:
        current_user: Current authenticated user from dependency

    Returns:
        Token verification result with user information
    """
    return TokenVerificationResponse(
        valid=True,
        user={
            "id": current_user["user_id"],
            "email": current_user["email"],
            "profile": current_user["profile"]
        }
    )


@router.post(
    "/sync-profile",
    response_model=ProfileSyncResponse,
    summary="Sync User Profile",
    description="Synchronize user profile data from Supabase Auth to the profiles table.",
    response_description="Profile synchronization result",
    operation_id="syncUserProfile",
    responses={
        200: {
            "description": "Profile synchronized successfully",
            "content": {
                "application/json": {
                    "examples": {
                        "created": {
                            "summary": "Profile created",
                            "value": {"message": "User profile created successfully"}
                        },
                        "updated": {
                            "summary": "Profile updated",
                            "value": {"message": "User profile updated successfully"}
                        }
                    }
                }
            }
        },
        **get_common_responses(401, 500)
    }
)
async def sync_user_profile(
    current_user: CurrentUser,
    auth_service: SupabaseAuthServiceDep,
) -> ProfileSyncResponse:
    """
    Sync user profile from Supabase Auth to profiles table.

    This endpoint ensures that the user profile in the profiles table
    is synchronized with the Supabase Auth user data. It will create
    a new profile if one doesn't exist, or update the existing profile.

    **Use Case:** Call this after OAuth login to ensure profile data is up-to-date
    with the latest information from the authentication provider.

    **Authentication Required:** Bearer token from Supabase Auth

    Args:
        current_user: Current authenticated user from dependency
        auth_service: Supabase authentication service

    Returns:
        Success message indicating whether profile was created or updated
    """
    try:
        # Delegate sync logic to service
        action = await auth_service.sync_profile(
            user_id=current_user["user_id"],
            email=current_user["email"],
            user_metadata=current_user.get("user_metadata", {})
        )

        return ProfileSyncResponse(message=f"User profile {action} successfully")

    except Exception as e:
        raise HTTPException(
            status_code=http_status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to sync user profile"
        )
