[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "builder"
version = "0.0.1"
dependencies = [
    "backend",
    "requests"
]

[tool.hatch.build.targets.wheel]
packages = ["."]
